notifications:
  email: false

sudo: false
language: python
python: '3.6'
cache: pip

install:
  - pip install tox

script:
  - mkdir /tmp/python35bin/
  - ln -s ~/virtualenv/python3.5/bin/python /tmp/python35bin/python3.5
  - export PATH=$PATH:/tmp/python35bin
  - tox
